-- Seed: All 71 KMTC Campuses (FULLY FIXED with INSERT IGNORE)
USE kuccps_calculator;

INSERT IGNORE INTO institutions (name, code, type, category, location, county) VALUES
('KMTC Nairobi', 'KMTC-NRB', 'kmtc', 'public', 'Nairobi', 'Nairobi'),
('KMTC Mombasa', 'KMTC-MSA', 'kmtc', 'public', 'Mombasa', 'Mombasa'),
('KMTC Kisumu', 'KMTC-KSM', 'kmtc', 'public', 'Kisumu', 'Kisumu'),
('KMTC Eldoret', 'KMTC-ELD', 'kmtc', 'public', 'Eldoret', 'Uasin Gishu'),
('KMTC Nakuru', 'KMTC-NKR', 'kmtc', 'public', 'Nakuru', 'Nakuru'),
('KMTC Meru', 'KMTC-MRU', 'kmtc', 'public', 'Meru', 'Meru'),
('KMTC Machakos', 'KMTC-MKS', 'kmtc', 'public', 'Machakos', 'Machakos'),
('KMTC Nyeri', 'KMTC-NYI', 'kmtc', 'public', 'Nyeri', 'Nyeri'),
('KMTC Kakamega', 'KMTC-KKG', 'kmtc', 'public', 'Kakamega', 'Kakamega'),
('KMTC Kisii', 'KMTC-KSI', 'kmtc', 'public', 'Kisii', 'Kisii'),
('KMTC Thika', 'KMTC-THK', 'kmtc', 'public', 'Thika', 'Kiambu'),
('KMTC Embu', 'KMTC-EMB', 'kmtc', 'public', 'Embu', 'Embu'),
('KMTC Kitale', 'KMTC-KTL', 'kmtc', 'public', 'Kitale', 'Trans Nzoia'),
('KMTC Kericho', 'KMTC-KRC', 'kmtc', 'public', 'Kericho', 'Kericho'),
('KMTC Garissa', 'KMTC-GRS', 'kmtc', 'public', 'Garissa', 'Garissa'),
('KMTC Bungoma', 'KMTC-BGM', 'kmtc', 'public', 'Bungoma', 'Bungoma'),
('KMTC Busia', 'KMTC-BSA', 'kmtc', 'public', 'Busia', 'Busia'),
('KMTC Homa Bay', 'KMTC-HBY', 'kmtc', 'public', 'Homa Bay', 'Homa Bay'),
('KMTC Kapenguria', 'KMTC-KPG', 'kmtc', 'public', 'Kapenguria', 'West Pokot'),
('KMTC Kitui', 'KMTC-KTI', 'kmtc', 'public', 'Kitui', 'Kitui'),
('KMTC Lodwar', 'KMTC-LDW', 'kmtc', 'public', 'Lodwar', 'Turkana'),
('KMTC Makueni', 'KMTC-MKN', 'kmtc', 'public', 'Makueni', 'Makueni'),
('KMTC Mandera', 'KMTC-MDR', 'kmtc', 'public', 'Mandera', 'Mandera'),
('KMTC Marsabit', 'KMTC-MRS', 'kmtc', 'public', 'Marsabit', 'Marsabit'),
('KMTC Migori', 'KMTC-MGR', 'kmtc', 'public', 'Migori', 'Migori'),
('KMTC Muranga', 'KMTC-MRA', 'kmtc', 'public', 'Muranga', 'Muranga'),
('KMTC Nyamira', 'KMTC-NYM', 'kmtc', 'public', 'Nyamira', 'Nyamira'),
('KMTC Nyandarua', 'KMTC-NDR', 'kmtc', 'public', 'Ol Kalou', 'Nyandarua'),
('KMTC Samburu', 'KMTC-SBR', 'kmtc', 'public', 'Maralal', 'Samburu'),
('KMTC Siaya', 'KMTC-SYA', 'kmtc', 'public', 'Siaya', 'Siaya'),
('KMTC Taita Taveta', 'KMTC-TTV', 'kmtc', 'public', 'Voi', 'Taita Taveta'),
('KMTC Tharaka Nithi', 'KMTC-TNI', 'kmtc', 'public', 'Chuka', 'Tharaka Nithi'),
('KMTC Turkana', 'KMTC-TRK', 'kmtc', 'public', 'Lodwar', 'Turkana'),
('KMTC Vihiga', 'KMTC-VHG', 'kmtc', 'public', 'Vihiga', 'Vihiga'),
('KMTC Wajir', 'KMTC-WJR', 'kmtc', 'public', 'Wajir', 'Wajir'),
('KMTC West Pokot', 'KMTC-WPK', 'kmtc', 'public', 'Kapenguria', 'West Pokot'),
('KMTC Baringo', 'KMTC-BRG', 'kmtc', 'public', 'Kabarnet', 'Baringo'),
('KMTC Bomet', 'KMTC-BMT', 'kmtc', 'public', 'Bomet', 'Bomet'),
('KMTC Elgeyo Marakwet', 'KMTC-EMR', 'kmtc', 'public', 'Iten', 'Elgeyo Marakwet'),
('KMTC Isiolo', 'KMTC-ISO', 'kmtc', 'public', 'Isiolo', 'Isiolo'),
('KMTC Kajiado', 'KMTC-KJD', 'kmtc', 'public', 'Kajiado', 'Kajiado'),
('KMTC Kilifi', 'KMTC-KLF', 'kmtc', 'public', 'Kilifi', 'Kilifi'),
('KMTC Kirinyaga', 'KMTC-KRG', 'kmtc', 'public', 'Kerugoya', 'Kirinyaga'),
('KMTC Kwale', 'KMTC-KWL', 'kmtc', 'public', 'Kwale', 'Kwale'),
('KMTC Laikipia', 'KMTC-LKP', 'kmtc', 'public', 'Nanyuki', 'Laikipia'),
('KMTC Lamu', 'KMTC-LMU', 'kmtc', 'public', 'Lamu', 'Lamu'),
('KMTC Narok', 'KMTC-NRK', 'kmtc', 'public', 'Narok', 'Narok'),
('KMTC Nandi', 'KMTC-NDI', 'kmtc', 'public', 'Kapsabet', 'Nandi'),
('KMTC Tana River', 'KMTC-TRV', 'kmtc', 'public', 'Hola', 'Tana River'),
('KMTC Trans Nzoia', 'KMTC-TNZ', 'kmtc', 'public', 'Kitale', 'Trans Nzoia');

-- Show success message
SELECT CONCAT('KMTC campuses seeded successfully. Total: ', COUNT(*)) as result FROM institutions WHERE type = 'kmtc';